/**
 * "Commons Clause" License Condition v1.0
 *
 * The Software is provided to you by the Licensor under the License, as defined
 * below, subject to the following condition.
 *
 * Without limiting other conditions in the License, the grant of rights under the
 * License will not include, and the License does not grant to you, the right to
 * Sell the Software.
 *
 * For purposes of the foregoing, “Sell” means practicing any or all of the rights
 * granted to you under the License to provide to third parties, for a fee or
 * other consideration (including without limitation fees for hosting or
 * consulting/ support services related to the Software), a product or service
 * whose value derives, entirely or substantially, from the functionality of the
 * Software. Any license notice or attribution required by the License must also
 * include this Commons Clause License Condition notice.
 *
 * Software: Infinitic
 *
 * License: MIT License (https://opensource.org/licenses/MIT)
 *
 * Licensor: infinitic.io
 */

package io.infinitic.exceptions

import io.infinitic.common.json.Json
import io.infinitic.common.serDe.SerializedData
import io.infinitic.common.tasks.Constants
import io.infinitic.common.tasks.data.TaskOptions
import io.infinitic.workflows.Channel
import kotlinx.serialization.Serializable

@Serializable
sealed class UserException : RuntimeException()

@Serializable
sealed class UserExceptionInSerialization(
    val msg: String,
    val help: String
) : UserException() {
    override val message = "$msg.\n$help"
}

@Serializable
sealed class UserExceptionInClient(
    val msg: String,
    val help: String
) : UserException() {
    override val message = "$msg.\n$help"
}

@Serializable
sealed class UserExceptionInWorker(
    val msg: String,
    val help: String
) : UserException() {
    override val message = "$msg.\n$help"
}

@Serializable
sealed class UserExceptionInWorkflowTask(
    val msg: String,
    val help: String
) : UserException() {
    override val message = "$msg.\n$help"
}

/***********************
 * Exceptions during serialization
 ***********************/

@Serializable
data class MissingMetaJavaClassDuringDeserialization(
    val data: SerializedData
) : UserExceptionInSerialization(
    msg = "Trying to deserialize data without explicitly providing java class in \"${SerializedData.META_JAVA_CLASS}\" meta value",
    help = "You are probably trying to deserialize data generated by non-Java code. " +
        "Update this non-java code to include a \"${SerializedData.META_JAVA_CLASS}\" meta value " +
        "describing the java class that should be used"
)

@Serializable
data class ClassNotFoundDuringDeserialization(
    val data: SerializedData,
    val name: String
) : UserExceptionInSerialization(
    msg = "Trying to deserialize data into \"$name\$ (according to \"${SerializedData.META_JAVA_CLASS}\" meta value) but this class is unknown",
    help = "Please make sure to include the \"$name\" class in your code base."
)

@Serializable
data class SerializerNotFoundDuringDeserialization(
    val name: String
) : UserExceptionInSerialization(
    msg = "Trying to deserialize data into \"$name\$ but this class has no serializer",
    help = "Your data was correctly serialized, so make sure you use the same code base everywhere"
)

@Serializable
data class ExceptionDuringKotlinDeserialization(
    val name: String,
    val causeString: String
) : UserExceptionInSerialization(
    msg = "Trying to deserialize data into \"$name\$ but an error occurred during Kotlin deserialization: $causeString",
    help = "Please make sure your class \"$name\$ can be safely serialized/deserialized using kotlinx.serialization and avro4k"
)

@Serializable
data class ExceptionDuringJsonDeserialization(
    val name: String,
    val causeString: String
) : UserExceptionInSerialization(
    msg = "Trying to deserialize data into \"$name\$ but an error occurred during json deserialization: $causeString",
    help = "Please make sure your class \"$name\$ can be safely serialized/deserialized in Json using FasterXML/jackson"
)

@Serializable
data class ErrorDuringJsonSerializationOfParameter(
    val parameterName: String,
    val parameterType: String,
    val methodName: String,
    val className: String
) : UserExceptionInSerialization(
    msg = "Error during Json serialization of parameter $parameterName of $className::$methodName",
    help = "We are using Jackson library per default to serialize object through the ${Json::class.java.name} wrapper. If an exception is thrown during serialization, please consider those options:\n" +
        "- modifying $parameterType to make it serializable by ${Json::class.java.name}\n" +
        "- replacing $parameterType per simpler parameters in $className::$methodName\n"
)

@Serializable
data class ErrorDuringJsonDeserializationOfParameter(
    val parameterName: String,
    val parameterType: String,
    val methodName: String,
    val className: String
) : UserExceptionInSerialization(
    msg = "Error during Json de-serialization of parameter $parameterName of $className::$methodName",
    help = "We are using Jackson library per default to serialize/deserialize object through the ${Json::class.java.name} wrapper. If an exception is thrown during serialization or deserialization, please consider those options:\n" +
        "- modifying $parameterType to make it serializable by ${Json::class.java.name}\n" +
        "- replacing $parameterType per simpler parameters in $className::$methodName\n"
)

@Serializable
data class InconsistentJsonSerializationOfParameter(
    val parameterName: String,
    val parameterType: String,
    val methodName: String,
    val className: String
) : UserExceptionInSerialization(
    msg = "Serializated and deserialized value of parameter $parameterName of $className::$methodName are not equal",
    help = "We are using Jackson library per default to serialize/deserialize object through the ${Json::class.java.name} wrapper. If an exception is thrown during serialization or deserialization, consider those options:\n" +
        "- modifying $parameterType to make it serializable by ${Json::class.java.name}\n" +
        "- replacing $parameterType per simpler parameters in $className::$methodName\n" +
        "- update \"equals\" method of $parameterType to make sure that 2 different instances with same internal values are equal"
)

/***********************
 * Exceptions in client
 ***********************/

@Serializable
data class NotAStub(
    val name: String,
    val async: String
) : UserExceptionInClient(
    msg = "The first parameter of the client.$async(.) function should be a stub",
    help = "Make sure to provide the stub provided by a client.task($name) or client.workflow($name) function."
)

@Serializable
data class IncorrectExistingStub(
    val name: String,
    val type: String
) : UserExceptionInClient(
    msg = "The first parameter of the client.async(.) function should be the stub of an existing $type",
    help = "Make sure to provide the stub returned by client.$type($name, id) function, with an id."
)

@Serializable
data class IncorrectNewStub(
    val name: String,
    val async: String,
    val type: String
) : UserExceptionInClient(
    msg = "The first parameter of the client.$async(.) function should be the stub of a new $type",
    help = "Make sure to provide the stub returned by client.$type($name), without id."
)

@Serializable
data class SuspendMethodNotSupported(
    val name: String,
    val method: String
) : UserExceptionInClient(
    msg = "method \"$method\" in class \"$name\" is a suspend function",
    help = "Suspend functions are not supported"
)

@Serializable
data class NoMethodCall(
    val name: String
) : UserExceptionInClient(
    msg = "The method to call for your task or workflow is missing",
    help = "Make sure to call a method of \"$name\" in the second parameter of client.async()"
)

@Serializable
data class NoSendMethodCall(
    val className: String,
    val channelName: String
) : UserExceptionInClient(
    msg = "Nothing to send for $className::$channelName",
    help = "Make sure to call the \"send\" method in the second parameter of client.async($channelName())"
)

@Serializable
data class MultipleMethodCalls(
    val name: String,
    val method1: String?,
    val method2: String
) : UserExceptionInClient(
    msg = "Only one method of \"$name\" can be dispatched at a time. You can not call \"$method2\" method as you have already called \"$method1\"",
    help = "Make sure you call only one method of \"$name\" - multiple calls in the provided lambda is forbidden"
)

/***********************
 * Exceptions in task executor
 ***********************/

@Serializable
data class ClassNotFoundDuringInstantiation(
    val name: String
) : UserExceptionInWorker(
    msg = "Impossible to find a Class associated to $name",
    help = "Use \"register\" method to provide an instance that will be used associated to $name"
)

@Serializable
data class NoMethodFoundWithParameterTypes(
    val klass: String,
    val method: String,
    val parameterTypes: List<String>
) : UserExceptionInWorker(
    msg = "No method \"$method(${ parameterTypes.joinToString() })\" found in \"$klass\" class",
    help = "Make sure parameter types are consistent with your method definition"
)

@Serializable
data class NoMethodFoundWithParameterCount(
    val klass: String,
    val method: String,
    val parameterCount: Int
) : UserExceptionInWorker(
    msg = "No method \"$method\" with $parameterCount parameters found in \"$klass\" class",
    help = ""
)

@Serializable
data class TooManyMethodsFoundWithParameterCount(
    val klass: String,
    val method: String,
    val parameterCount: Int
) : UserExceptionInWorker(
    msg = "Unable to decide which method \"$method\" with $parameterCount parameters to use in \"$klass\" class",
    help = ""
)

@Serializable
data class RetryDelayHasWrongReturnType(
    val klass: String,
    val actualType: String,
    val expectedType: String
) : UserExceptionInWorker(
    msg = "In \"$klass\" class, method ${Constants.DELAY_BEFORE_RETRY_METHOD} returns a $actualType, it must be a $expectedType",
    help = "Please update your method definition to return a $expectedType (or null)"
)

@Serializable
data class ProcessingTimeout(
    val klass: String,
    val delay: Float
) : UserExceptionInWorker(
    msg = "The processing of task \"$klass\" took more than $delay seconds",
    help = "You can increase (or remove entirely) this constraint in the options ${TaskOptions::javaClass.name}"
)

/***********************
 * Exceptions in workflow tasks
 ***********************/

@Serializable
data class WorkflowUpdatedWhileRunning(
    val workflowName: String,
    val workflowMethodName: String,
    val position: String
) : UserExceptionInWorkflowTask(
    msg = "Definition of workflow \"$workflowName\" has been updated since its launch (detected at position $position in $workflowMethodName)",
    help = "You can either kill this instance or revert its previous definition to be able to resume it"
)

@Serializable
data class NoMethodCallAtAsync(
    val name: String
) : UserExceptionInWorkflowTask(
    msg = "You must use a method of \"$name\" when using \"async\" method",
    help = "Make sure to call exactly one method of \"$name\" within the curly braces - example: async(foo) { bar(*args) }"
)

@Serializable
data class ShouldNotWaitInsideInlinedTask(
    val method: String
) : UserExceptionInWorkflowTask(
    msg = "You must not suspend computations inside an inlined task",
    help = "In $method, make sure you do not wait for task or child workflow completion inside `task { ... }`"
)

@Serializable
data class ShouldNotUseAsyncFunctionInsideInlinedTask(
    val method: String
) : UserExceptionInWorkflowTask(
    msg = "You must not suspend computations inside an inlined task",
    help = "In $method, make sure you do not use `async { ... }` function inside `task { ... }`"
)

@Serializable
data class WorkflowUsedAsTask(
    val name: String,
    val workflow: String
) : UserExceptionInWorkflowTask(
    msg = "$name is used as a task, but registered implementation $workflow is a workflow",
    help = "Check that you are using $name consistently between client and workers"
)

@Serializable
data class TaskUsedAsWorkflow(
    val name: String,
    val task: String
) : UserExceptionInWorkflowTask(
    msg = "$name is used as a workflow, but registered implementation $task is a task",
    help = "Check that you are using $name consistently between client and workers"
)

@Serializable
data class ParametersInChannelMethod(
    val workflowName: String,
    val methodName: String
) : UserExceptionInWorkflowTask(
    msg = "in workflow $workflowName, method $methodName returning a ${Channel::class.simpleName} should NOT have any parameter",
    help = ""
)

@Serializable
data class NonUniqueChannelFromChannelMethod(
    val workflowName: String,
    val methodName: String
) : UserExceptionInWorkflowTask(
    msg = "in workflow $workflowName, method $methodName should return the same ${Channel::class.simpleName} instance when called multiple times",
    help = ""
)

@Serializable
data class MultipleNamesForChannel(
    val workflowName: String,
    val methodName: String,
    val otherName: String
) : UserExceptionInWorkflowTask(
    msg = "in workflow $workflowName, method $methodName return a ${Channel::class.simpleName} instance already associated with name $otherName",
    help = "Make sure to not have multiple methods returning the same channel"
)

@Serializable
object NameNotInitializedInChannel : UserExceptionInWorkflowTask(
    msg = "A ${Channel::class.simpleName} is used without name",
    help = "Make sure to have a method that returns this channel."
)
