/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application.
    application
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${project.extra["kotlinx_coroutines_version"]}")
    implementation("org.apache.pulsar:pulsar-client:${project.extra["pulsar_version"]}")
    implementation("org.apache.pulsar:pulsar-functions-api:${project.extra["pulsar_version"]}")
    implementation("com.sksamuel.hoplite:hoplite-core:${project.extra["hoplite_version"]}")
    implementation("com.sksamuel.hoplite:hoplite-yaml:${project.extra["hoplite_version"]}")

    api(project(":infinitic-client"))
    api(project(":infinitic-worker-pulsar"))
    api(project(":infinitic-task-executor"))
}

application {
    // Define the main class for the application.
    mainClassName = "my.infinitic.project.MainKt"
}
