/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zenaton.sdk

import java.lang.reflect.Proxy

inline fun <reified T> proxyTask(): T {
    return Proxy.newProxyInstance(
        T::class.java.classLoader,
        kotlin.arrayOf(T::class.java),
        ProxyTaskHandler()
    ) as T
}

inline fun <reified T> proxyWorkflow(): T {
    return Proxy.newProxyInstance(
        T::class.java.classLoader,
        kotlin.arrayOf(T::class.java),
        ProxyWorkflowHandler()
    ) as T
}
